### ISSUE TITLE
Computer on windows 22H2 has different prefetch files for explorer and potentially other programs.

### ISSUE THREAD

**Issue by NoahMoyer** [NoahMoyer/AccessTimeAnalyzer#2]
Initial testing shows that a computer on Windows 10 22H2 has all different prefetch files compared to a computer with windows 21H2. Thinking about a solution that checks for either of the two different prefetch names for each app to handle this issue.

**Comment by nathanaelmoyer** [comment]
We can also check the system build number via the registry
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\
Key: CurrentBuildNumber

21H2 (19044)
![Screenshot 2022-12-14 093516](https://user-images.githubusercontent.com/36149055/207623866-41fe3437-dd32-4651-a74e-d2245a841e50.png)

My thought it we could create a different app group file for systems newer than 21H2 with the different prefetch file names and add a check in the program see what the system build is being checked. 

I'm also wondering with this discovery if we need to think of a more centralized data base of information for prefetch file names and install locations.

**Comment by NoahMoyer** [comment]
With the ability to reliably get the windows version of the computer we are looking at analyzing we are working on changing the functionality to store our app data in a database that we will query tables that will contain information for each version of windows that we maintain. I have created a version of the app that can now do this and will work on transferring data into the database.

**Comment by NoahMoyer** [comment]
Sql database implementation now is functional. Once the database contains all the information this issue will considered closed.

**Comment by NoahMoyer** [comment]
Database has been set up and app is now configured to ignore the prefetch file name. Now users only need a exe location and a name for the app they are looking at.
